### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by voxvox** [clostra/newnode#106] opened 2021-10-19 14:46 UTC
using latest android sdk ver 1.9.8, we see this crash in Firabase Crashlytics:

Fatal Exception: java.lang.UnsatisfiedLinkError 

No implementation found for void com.clostra.newnode.internal.NewNode.unregisterProxy() (tried Java_com_clostra_newnode_internal_NewNode_unregisterProxy and Java_com_clostra_newnode_internal_NewNode_unregisterProxy__)

stacktrace here:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.clostra.newnode.internal.NewNode.unregisterProxy() (tried Java_com_clostra_newnode_internal_NewNode_unregisterProxy and Java_com_clostra_newnode_internal_NewNode_unregisterProxy__)
       at com.clostra.newnode.internal.NewNode.unregisterProxy(NewNode.java)
       at com.clostra.newnode.internal.NewNode.shutdown(NewNode.java:208)
       at com.clostra.newnode.NewNode.shutdown(NewNode.java:92)
       at org.rferl.utils.proxy.ProxyManager.onNext(ProxyManager.java:196)
       at org.rferl.utils.proxy.ProxyManager$$InternalSyntheticLambda$1$5e9cc9bec49b07c6bfd4644f25dce2c918b8a46028e1ce4dd8a1dc84dacd6ea5$0.accept(ProxyManager.java:4)
       at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


```

**Comment by ghazel** [comment] 2021-11-08 11:02
This is almost certainly a device that could not load the newnode native library. Do you have device info like make, model, and Android version?

**Comment by voxvox** [comment] 2021-11-08 11:18
Android ver / Device
---------------------
8.1.0 / Nexus 5X
5.1 / Motorola One Vision
5.1 / vivo S1

**Comment by flyinhome** [comment] 2021-11-24 20:45
Whenever I've seen `java.lang.UnsatisifiedLinkError` the cause has always been an earlier failure to load a native library.  If you have logcat output from the run there should be an error message (perhaps associated with a call to `dlopen`) before the `java.lang.UnsatisfiedLinkError` message complaining about that load failure.   In my experience such failures are sometimes caused by missing symbols, but load failures can occur for other reasons.

**Comment by Petr-Kubista** [comment] 2021-11-25 12:27
Unfortunately, this is not something we can replicate and the logcat is not a part of Firebase Crashlytics report.

**Comment by flyinhome** [comment] 2021-11-26 00:14
I don't know if this helps but since the missing symbol is
com.clostra.newnode.internal.NewNode.unregisterProxy()
this is part of the JNI code in newnode/android.c
So it's the newnode library itself that isn't being loaded.

I believe that the code that loads this is in newnode/android/src/main/java/com/clostra/newnode/internal/NewNode.java
in 
```
public class NewNode implements NewNodeInternal, Runnable {
    public static String VERSION = BuildConfig.VERSION_NAME;

    static Thread t;
    //static Thread updateThread;
    static boolean requestPermission = true;
    static NearbyHelper nearbyHelper;
    static Client bugsnagClient;

    static {
        Application app = app();

        File[] files = app.getFilesDir().listFiles();
        Arrays.sort(files);
        for (int i = files.length - 1; i >= 0; i--) {
            File f = files[i];
            try {
                Matcher m = Pattern.compile("^libnewnode.v?([.0-9]*).so$").matcher(f.getName());
                if (!m.find()) {
                    continue;
                }
                String v2 = m.group(1);
                if (VERSION.compareTo(v2) < 0) {
                    Log.d("newnode", "loading "+f.getName());
                    System.load(f.getAbsolutePath());
                    VERSION = v2;
                    break;
                }
            } catch (Exception e) {
                Log.e("newnode", "", e);
            }
        }
        // XXX: might not work in a classes.dex
        if (VERSION.equals(BuildConfig.VERSION_NAME)) {
            try {
                Log.d("newnode", "loading built-in newnode");
                System.loadLibrary("newnode");
            } catch (UnsatisfiedLinkError e) {
                Log.e("newnode", "", e);
            }
        }
```

(the call to System.loadLibrary() is near the end)

The exception handler after that call to `System.loadLibrary` calls `Log.e` to print out the exception and associated error message (for example, which symbol in the newnode library that the Java code needs, is not found).   If you're not capturing Log messages, could you perhaps change that exception handler, or maybe just temporarily delete the exception handler so that the program will crash but reveal more detail about the error?

**Comment by Petr-Kubista** [comment] 2022-02-01 13:00
We managed to reproduce the issue on an emulator - Pixel 4 with Android API 30 - Google Play x86 system image.

Getting these errors:
```
2022-02-01 13:56:50.173 12702-12702/gov.bbg.voa D/newnode: Loading built-in NewNodeInternal
2022-02-01 13:56:50.182 12702-12702/gov.bbg.voa D/NearbyHelper: loading built-in newnode
2022-02-01 13:56:50.191 12702-12702/gov.bbg.voa E/NearbyHelper: java.lang.UnsatisfiedLinkError: dlopen failed: library "libnewnode.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.clostra.newnode.internal.NewNode.<clinit>(NewNode.java:89)
        at java.lang.Class.newInstance(Native Method)
        at com.clostra.newnode.NewNode.<clinit>(NewNode.java:67)
        at com.clostra.newnode.NewNode.shutdown(NewNode.java:92)
        at org.rferl.utils.proxy.ProxyManager.onNext(ProxyManager.java:176)
        at org.rferl.utils.proxy.ProxyManager$$ExternalSyntheticLambda1.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
        at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2022-02-01 13:56:50.218 12702-12702/gov.bbg.voa E/gov.bbg.voa: No implementation found for void com.clostra.newnode.internal.NewNode.unregisterProxy() (tried Java_com_clostra_newnode_internal_NewNode_unregisterProxy and Java_com_clostra_newnode_internal_NewNode_unregisterProxy__)
```

Is that something you can fix on your side, or do we need to wrap NewNode calls in try-catch blocks?

**Comment by ghazel** [comment] 2022-02-01 13:15
The intention is not to need to wrap NewNode calls. How do you reproduce the issue?

**Comment by ghazel** [comment] 2022-02-01 13:28
NewNode does not support x86 Android. It does support x86_64.

**Comment by Petr-Kubista** [comment] 2022-02-01 14:44
Right, that definitely explains the crashes on emulator. I suppose the real device crashes might have the same cause. Do you have a list of supported ABIs I could check against in code and decide if NewNode should be loaded at all?

**Comment by ghazel** [comment] 2022-02-01 14:46
armeabi-v7a, arm64-v8a, x86_64
https://github.com/clostra/newnode/blob/master/build.android.sh#L119

That should cover all real-world devices.

**Comment by Petr-Kubista** [comment] 2022-02-01 15:06
Thanks, I'll make sure only to use NewNode on 64bit ABIs. You can close this ticket, I'll re-open it if the issue persists.

**Comment by ghazel** [comment] 2022-02-01 15:08
armeabi-v7a is 32 bit.

**Closed as completed** 2022-02-01 15:09 UTC
